manifest:
  remotes:
    - name: LucaPatarca
      url-base: https://github.com/LucaPatarca
  projects:
    - name: zmk
      remote: LucaPatarca
      revision: main
      import: app/west.yml
  self:
    path: config
